import { RecruitmentType } from "@/types";

const Recruitments: RecruitmentType[] = [
  {
    title: "UI UX Designer",
    isActive: true,
    company: "Unpixel HQ",
    position: "Designer",
    createdTime: "Created 3m ago",
    applicants: [
      {
        name: "Lincoln Torff",
        email: "lincoln@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "applied",
        createdTime: "",
      },
      {
        name: "Hanna Baptista",
        email: "hanna@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "screening",
        createdTime: "",
      },
      {
        name: "Miracle Geidt",
        email: "miracle@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "1st interview",
        createdTime: "",
      },
      {
        name: "Rayna Torff",
        email: "rayna@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "2nd interview",
        createdTime: "",
      },
      {
        name: "Giana Lipshutz",
        email: "giana@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "hiring",
        createdTime: "",
      },
      {
        name: "James George",
        email: "james@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "hiring",
        createdTime: "",
      },
      {
        name: "Jordyn George",
        email: "jordyn@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "rejected",
        createdTime: "",
      },
      {
        name: "Skylar Herwitz",
        email: "skylar@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "screening",
        createdTime: "",
      },
      {
        name: "Jordyn George",
        email: "jordyn@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "rejected",
        createdTime: "",
      },
      {
        name: "Skylar Herwitz",
        email: "skylar@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "screening",
        createdTime: "",
      },
    ],
  },
  {
    title: "UI UX Designer",
    isActive: true,
    company: "Unpixel HQ",
    position: "Designer",
    createdTime: "Created 3m ago",
    applicants: [
      {
        name: "Lincoln Torff",
        email: "lincoln@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "applied",
        createdTime: "",
      },
      {
        name: "Hanna Baptista",
        email: "hanna@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "screening",
        createdTime: "",
      },
      {
        name: "Miracle Geidt",
        email: "miracle@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "1st interview",
        createdTime: "",
      },
      {
        name: "Rayna Torff",
        email: "rayna@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "2nd interview",
        createdTime: "",
      },
      {
        name: "Giana Lipshutz",
        email: "giana@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "hiring",
        createdTime: "",
      },
      {
        name: "James George",
        email: "james@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "hiring",
        createdTime: "",
      },
      {
        name: "Jordyn George",
        email: "jordyn@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "rejected",
        createdTime: "",
      },
      {
        name: "Skylar Herwitz",
        email: "skylar@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "screening",
        createdTime: "",
      },
      {
        name: "Jordyn George",
        email: "jordyn@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "rejected",
        createdTime: "",
      },
      {
        name: "Skylar Herwitz",
        email: "skylar@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "screening",
        createdTime: "",
      },
    ],
  },
  {
    title: "UI UX Designer",
    isActive: true,
    company: "Unpixel HQ",
    position: "Designer",
    createdTime: "Created 3m ago",
    applicants: [
      {
        name: "Lincoln Torff",
        email: "lincoln@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "applied",
        createdTime: "",
      },
      {
        name: "Hanna Baptista",
        email: "hanna@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "screening",
        createdTime: "",
      },
      {
        name: "Miracle Geidt",
        email: "miracle@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "1st interview",
        createdTime: "",
      },
      {
        name: "Rayna Torff",
        email: "rayna@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "2nd interview",
        createdTime: "",
      },
      {
        name: "Giana Lipshutz",
        email: "giana@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "hiring",
        createdTime: "",
      },
      {
        name: "James George",
        email: "james@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "hiring",
        createdTime: "",
      },
      {
        name: "Jordyn George",
        email: "jordyn@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "rejected",
        createdTime: "",
      },
      {
        name: "Skylar Herwitz",
        email: "skylar@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "screening",
        createdTime: "",
      },
      {
        name: "Jordyn George",
        email: "jordyn@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "rejected",
        createdTime: "",
      },
      {
        name: "Skylar Herwitz",
        email: "skylar@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "screening",
        createdTime: "",
      },
    ],
  },
  {
    title: "UI UX Designer",
    isActive: true,
    company: "Unpixel HQ",
    position: "Designer",
    createdTime: "Created 3m ago",
    applicants: [
      {
        name: "Lincoln Torff",
        email: "lincoln@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "applied",
        createdTime: "",
      },
      {
        name: "Hanna Baptista",
        email: "hanna@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "screening",
        createdTime: "",
      },
      {
        name: "Miracle Geidt",
        email: "miracle@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "1st interview",
        createdTime: "",
      },
      {
        name: "Rayna Torff",
        email: "rayna@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "2nd interview",
        createdTime: "",
      },
      {
        name: "Giana Lipshutz",
        email: "giana@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "hiring",
        createdTime: "",
      },
      {
        name: "James George",
        email: "james@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "hiring",
        createdTime: "",
      },
      {
        name: "Jordyn George",
        email: "jordyn@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "rejected",
        createdTime: "",
      },
      {
        name: "Skylar Herwitz",
        email: "skylar@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "screening",
        createdTime: "",
      },
      {
        name: "Jordyn George",
        email: "jordyn@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "rejected",
        createdTime: "",
      },
      {
        name: "Skylar Herwitz",
        email: "skylar@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "screening",
        createdTime: "",
      },
    ],
  },
  {
    title: "UI UX Designer",
    isActive: true,
    company: "Unpixel HQ",
    position: "Designer",
    createdTime: "Created 3m ago",
    applicants: [
      {
        name: "Lincoln Torff",
        email: "lincoln@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "applied",
        createdTime: "",
      },
      {
        name: "Hanna Baptista",
        email: "hanna@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "screening",
        createdTime: "",
      },
      {
        name: "Miracle Geidt",
        email: "miracle@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "1st interview",
        createdTime: "",
      },
      {
        name: "Rayna Torff",
        email: "rayna@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "2nd interview",
        createdTime: "",
      },
      {
        name: "Giana Lipshutz",
        email: "giana@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "hiring",
        createdTime: "",
      },
      {
        name: "James George",
        email: "james@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "hiring",
        createdTime: "",
      },
      {
        name: "Jordyn George",
        email: "jordyn@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "rejected",
        createdTime: "",
      },
      {
        name: "Skylar Herwitz",
        email: "skylar@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "screening",
        createdTime: "",
      },
      {
        name: "Jordyn George",
        email: "jordyn@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "rejected",
        createdTime: "",
      },
      {
        name: "Skylar Herwitz",
        email: "skylar@unpixel.com",
        image: "",
        cv: "",
        phoneNumber: "08092139441",
        stage: "screening",
        createdTime: "",
      },
    ],
  },
];

export default Recruitments;
