import { Header, Sidebar } from "@/components";
import { Manrope } from "next/font/google";
import type { Metadata } from "next";
import styles from "./layout.module.css";
import "../globals.css";

const manrope = Manrope({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <div className={styles.wrapper}>
          <Sidebar />
          <div className={styles.content}>
            <div className={styles.header}>
              <Header />
            </div>

            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
