import { LayoutType } from "@/types";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: LayoutType) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
